openapi: 3.0.3
info:
  title: Todo Application Backend API
  description: |
    Secure RESTful API for task management with JWT authentication and user data isolation.

    ## Authentication
    All endpoints require JWT authentication via Bearer token in the Authorization header.
    Tokens are issued by Better Auth on the frontend and verified by the backend.

    ## User Isolation
    All operations are scoped to the authenticated user. Users can only access their own tasks.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8000
    description: Development server
  - url: http://localhost:8000/api
    description: API base path

security:
  - BearerAuth: []

tags:
  - name: tasks
    description: Task management operations
  - name: health
    description: Health check endpoints

paths:
  /health:
    get:
      tags:
        - health
      summary: Health check
      description: Check if the API is running
      security: []
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy

  /api/tasks:
    get:
      tags:
        - tasks
      summary: List all tasks for authenticated user
      description: |
        Retrieve all tasks belonging to the authenticated user.
        Supports filtering by completion status and sorting by various fields.
      parameters:
        - name: status
          in: query
          description: Filter tasks by completion status
          required: false
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
        - name: sort
          in: query
          description: Sort tasks by field
          required: false
          schema:
            type: string
            enum: [created, title, due_date]
            default: created
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      tags:
        - tasks
      summary: Create a new task
      description: Create a new task for the authenticated user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/tasks/{task_id}:
    get:
      tags:
        - tasks
      summary: Get a specific task
      description: Retrieve a specific task by ID (must belong to authenticated user)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      tags:
        - tasks
      summary: Update a task
      description: Update an existing task (must belong to authenticated user)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      tags:
        - tasks
      summary: Delete a task
      description: Delete an existing task (must belong to authenticated user)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /api/tasks/{task_id}/complete:
    patch:
      tags:
        - tasks
      summary: Toggle task completion status
      description: Toggle the completion status of a task (must belong to authenticated user)
      parameters:
        - name: task_id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Better Auth

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Optional detailed description
          example: "Write comprehensive API documentation with examples"
        completed:
          type: boolean
          description: Task completion status
          example: false
        priority:
          type: string
          nullable: true
          enum: [low, medium, high]
          description: Task priority level
          example: "high"
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Optional due date
          example: "2026-02-10T00:00:00Z"
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
          example: "2026-02-07T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-02-07T10:00:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Optional detailed description
          example: "Write comprehensive API documentation with examples"
        priority:
          type: string
          nullable: true
          enum: [low, medium, high]
          description: Task priority level
          example: "high"
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Optional due date
          example: "2026-02-10T00:00:00Z"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Updated task title"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Task description
          example: "Updated description"
        completed:
          type: boolean
          description: Task completion status
          example: true
        priority:
          type: string
          nullable: true
          enum: [low, medium, high]
          description: Task priority level
          example: "medium"
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Task due date
          example: "2026-02-15T00:00:00Z"

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

  responses:
    BadRequestError:
      description: Bad request - validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missingTitle:
              value:
                detail: "Task title is required"
            invalidPriority:
              value:
                detail: "Priority must be one of: low, medium, high"

    UnauthorizedError:
      description: Unauthorized - missing or invalid authentication token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missingToken:
              value:
                detail: "Missing authentication token"
            invalidToken:
              value:
                detail: "Invalid token"
            expiredToken:
              value:
                detail: "Token has expired"

    ForbiddenError:
      description: Forbidden - user does not have access to this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Not authorized to access this task"

    NotFoundError:
      description: Not found - resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found"
